---
clusterName: "elasticsearch"
nodeGroup: "master"

# The service that non master groups will try to connect to when joining the cluster
# This should be set to clusterName + "-" + nodeGroup for your master group
masterService: ""

# Elasticsearch roles that will be applied to this nodeGroup
# These will be set as environment variables. E.g. node.master=true
roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "true"
  ml: "true"

replicas: 3
minimumMasterNodes: 2

esMajorVersion: ""

clusterDeprecationIndexing: "false"

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig:
  elasticsearch.yml: |
    node.name: "elasticsearch01"
    cluster.name: "snss-logging-cluster"
    network.host: 0.0.0.0
    xpack.security.transport.ssl.enabled: false
    xpack.license.self_generated.type: basic
    xpack.security.enabled: true

antiAffinity: "soft"

extraEnvs:
   - name: ELASTIC_PASSWORD
     valueFrom:
        secretKeyRef:
           name: elastic-secret
           key: ELASTIC_PASSWORD

   - name: ELASTIC_USERNAME
     valueFrom:
        secretKeyRef:
           name: elastic-secret
           key: ELASTIC_USERNAME