apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-worker-mnt3-pv # Name of the PV. if the mnt1 is used by another service, it should be changed 
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  claimRef:
    name: redis-data-redis-replicas-0
    namespace: shift
  local:
    path: {mnt} # if the mnt1 is used by another service, it should be changed
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {hostname} # Change the value to the hostname of the node